### ISSUE TITLE
magneticraft lead ore yields silver

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#21]
`magneticraft:ores (#13033/1)`  yields silver in a Mechanical Squeezer. Recipes are shown yielding both lead and silver. A similar thing is visible in the smelting recipes, the melter (which yields different volumes and requires different temps), High Oven Melting, with the crusher and in a few otehr cases. The vanilla furnace gives a lead ingot, and basically everything else is messed up.

**Comment by ramou** [comment]
This seems to be a related ticket: https://github.com/Magneticraft-Team/Magneticraft/issues/70

**Comment by nicwatson** [comment]
Fixed in 1.1.0

Galena (magneticraft:ores#1) was listed in the ore dictionary as both a lead and silver ore, which is realistic but plays havoc with recipe consistency. It is now listed as only a lead ore.

Other mods already have nods to the real-world colocation of silver and lead in galena. In some crushers/grinders, crushing lead ores of any kind has a small chance to provide bonus silver, and crushing silvers has a small chance to yield bonus lead. Also, ThermalFoundation typically spawns lead and silver together in clusters.
