### ISSUE TITLE
Industrial Hemp does not support right-click harvest-replant

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#27]
Most other plants on tilled tiles can be right-clicked to gather their stuff and replant the seed. This is an effective and convenient way of doing gardening. It does not work with Industrial Hemp, where the block must be broken and manually replanted.

**Comment by nicwatson** [comment]
Industrial Hemp grows to double-height. The way IE's dev intended it to be used is that you let it grow to double height and then mow across the top block, leaving the bottom intact. That way, it will grow back without you needing to replant anything. I find this works well.

Certain crops grow in different ways that add some variety to gardening tasks -- less convenient perhaps, but also less boring. This is why, for instance, I've disabled Harvestcraft grapes and tomatoes (which just go in the ground like everything else in Harvestcraft) in favour of the Rustic versions that require stakes and ropes. Hemp follows a similar logic of trying to punctuate the monotony.

Generally, only Harvestcraft crops, plus vanilla crops (thanks to Harvestcraft), support right-click harvest. (Maybe Bewitchment too? It's on a per-mod basis anyway.) Quark has a feature to try to detect other crops and add right-click support but I turned it off because I was concerned that it would cause problems.

As always, I am open to changing these settings on the basis of broad player consensus.
