### ISSUE TITLE
Railcraft and Thermal Foundation Plates non-interchangeable in Engineering Workbench

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#29]
The same recipes exist for both, but you cannot have some of one type and some of another.

**Comment by nicwatson** [comment]
Must be a quirk in how the workbench handles oredict wildcards. 

Patch 1.2 will unify the plates so that it should be very difficult to accidentally acquire a nonstandard type for any plate, so in practice this problem should come up very rarely. Because plates are being standardized, the Tome of Standards will work on them too, so everyone can unify their plates.
