### ISSUE TITLE
Redundant Bronze Gear Recipe

### ISSUE THREAD

**Issue by ramou** [nicwatson/siegertsmiasma#8]
Therea re three. One takes 4xbronze ingot. One takes 4xbronze ingot, but with four sticks in the corners. The last takes 4xbronze ingot with a stone gear in the middle.

Probably the one built from the stone gear would be best/most consistent.

Note that copper gears have the same issue. Iron/steel gears have the stick and no-stick options (also redundant) but have no recipe requiring a stone gear. The other thermal craft gears just require the four elemental pieces (I think it'd be nice if they took the stone gear too, but hey)

**Comment by nicwatson** [comment]
Fixed in 1.1.0

Notes:
A CraftTweaker script to unify gears has been written and is now being tested.
Gears that are not used in any recipes will be disabled.
Gears of the same material will be unified to use a single type.
Gears can be made from four ingots of the appropriate type - no sticks, stone gear bases, or gear bushings required. (Requiring stone gear bases as suggested was considered, but the script is so much simpler if I don't have to do that.)
Gears can also be stamped using IE metal press or cast from molten metals using TConstruct (ingot cost is equivalent).

ClockworkPhase gears are a special case. They will be renamed as "finely tuned gears." To make them, a regular gear of the matching material must be put in a Railcraft rolling machine with some metal nuggets.

A finely tuned gear can be used in any recipe where a normal gear can be used. However, only the finely tuned gears can be used in precision clockwork.
